**Q1.** Write a Python program to convert kilometers to miles?

In [6]:
km= int(input('Enter value in Kilometers:'))
ml= km*0.62
print('{} km is equals to {} mile'.format(km, ml))

Enter value in Kilometers:5
5 km is equals to 3.1 mile

**Q2.** Write a Python program to convert Celsius to Fahrenheit?

In [9]:
cl= int(input('Enter value in Celsius:'))
fr= (cl*(9/5))+32
print('{} Celsius is equals to {} Fahrenheits'.format(cl, fr))

Enter value in Celsius:6
6 Celsius is equals to 42.8 Fahrenheits

**Q3.** Write a Python program to display calendar?

In [12]:
import calendar

year = int(input("Enter calender year: "))
print(calendar.calendar(year))

Enter calender year: 2001
                                  2001

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                1  2  3  4
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       5  6  7  8  9 10 11
15 16 17 18 19 20 21      12 13 14 15 16 17 18      12 13 14 15 16 17 18
22 23 24 25 26 27 28      19 20 21 22 23 24 25      19 20 21 22 23 24 25
29 30 31                  26 27 28                  26 27 28 29 30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1          1  2  3  4  5  6                   1  2  3
 2  3  4  5  6  7  8       7  8  9 10 11 12 13       4  5  6  7  8  9 10
 9 10 11 12 13 14 15      14 15 16 17 18 19 20      11 12 13 14 15 16 17
16 17 18 19 20 21 22      21 22 23 24 25 26 27      18 19 20 21 22 23 24
23 24 25 26 27 28 29      28 29 30 31               25 26 27 28 29 30
30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
                   1             1  2  3  4  5                      1  2
 2  3  4  5  6  7  8       6  7  8  9 10 11 12       3  4  5  6  7  8  9
 9 10 11 12 13 14 15      13 14 15 16 17 18 19      10 11 12 13 14 15 16
16 17 18 19 20 21 22      20 21 22 23 24 25 26      17 18 19 20 21 22 23
23 24 25 26 27 28 29      27 28 29 30 31            24 25 26 27 28 29 30
30 31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7                1  2  3  4                      1  2
 8  9 10 11 12 13 14       5  6  7  8  9 10 11       3  4  5  6  7  8  9
15 16 17 18 19 20 21      12 13 14 15 16 17 18      10 11 12 13 14 15 16
22 23 24 25 26 27 28      19 20 21 22 23 24 25      17 18 19 20 21 22 23
29 30 31                  26 27 28 29 30            24 25 26 27 28 29 30
                                                    31

**Q4.** Write a Python program to solve quadratic equation?

In [17]:
import cmath
import math

a= int(input('Enter the value pof a: '))
b= int(input('Enter the value pof b: '))
c= int(input('Enter the value pof c: '))

disc = b*b-4*a*c

if disc== 0:
    r1 = -b/2*a
    r2 = -b/2*a
    print("Roots are Real",r1,r2)
elif disc > 0:
    r1 = (-b-math.sqrt(disc))/(2 * a)
    r2 = (-b+math.sqrt(disc))/(2 * a)
    print("Roots are Real and different",r1,r2)
else:
    r1 = (-b-cmath.sqrt(disc))/(2 * a)
    r2 = (-b+cmath.sqrt(disc))/(2 * a)
    print("Roots are Imaginary",r1,r2)

Enter the value pof a: 3
Enter the value pof b: -2
Enter the value pof c: -4
Roots are Real and different -0.8685170918213297 1.5351837584879966

**Q5.** Write a Python program to swap two variables without temp variable?

In [20]:
num1 = int(input('Enter first number: '))
num2 = int(input('Enter second number: '))

num1 = num1+num2
num2 = num1-num2
num1 = num1-num2
print('Numbers are swaped: First= {}, Second= {}'.format(num1,num2))

Enter first number: 9
Enter second number: 15
Numbers are swaped: First= 15, Second= 9